setup-react:
	curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
	apt-get install -y nodejs
	apt-get install -y build-essential
	npm install -g create-react-app

start:
	npm start

build:
	npm run build
